# Generated by Django 5.1.2 on 2024-10-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_blog',
            new_name='image',
        ),
    ]
